services:
  nestjs:
    container_name: nestjs
    image: ${REGISTRY}/nest-js:${IMAGE_TAG}
    restart: always
    networks:
      - traefik-public
      - default
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.http.routers.nest-js.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.nest-js.middlewares=secure-headers
      - traefik.http.routers.nest-js.entryPoints=https
      - traefik.http.routers.nest-js.tls=true
      - traefik.http.routers.nest-js.tls.certResolver=letsEncrypt
      - traefik.http.services.nest-js.loadBalancer.server.port=3000
    environment:
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      DB_SYNCHRONIZE: ${DB_SYNCHRONIZE}

  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    networks:
      - default
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

networks:
  traefik-public:
    external: true


  DB_HOST=194.67.109.157
  DB_PORT=3306
  DB_USER=sabdev
  DB_PASSWORD="tB17zCQlpbdq"
  DB_NAME=sabtrans_test_dev
