name: Pipeline

on: push

env:
  REGISTRY: ghcr.io/${{ github.repository }}
  REGISTRY_HOST: ghcr.io
  REGISTRY_USERNAME: ${{ github.actor }}
  REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Docker login
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY_HOST }}
          username: ${{ env.REGISTRY_USERNAME }}
          password: ${{ env.REGISTRY_PASSWORD }}

      - name: Init
        run: make init

      - name: Lint
        run: make lint

      - name: Test
        run: make test

      - name: Down
        run: make docker-down-clear

  build:
    needs: analyze
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Docker login
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY_HOST }}
          username: ${{ env.REGISTRY_USERNAME }}
          password: ${{ env.REGISTRY_PASSWORD }}

      - name: Inject branch slug
        uses: rlespinasse/github-slug-action@v3.x

      - name: Set image tag
        run: echo "IMAGE_TAG=${GITHUB_REF_SLUG}-${GITHUB_RUN_NUMBER}" >> $GITHUB_ENV

      - name: Build
        run: make build-project

      - name: Push
        run: make push
